In [1]:
import numpy as np
import pandas as pd
import re
from unidecode import unidecode
from sqlalchemy import create_engine

In [2]:
#Importando dados brutos
df = pd.read_csv('../0_Bases_originais/nikebruto.csv', sep = ";")
df

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,
0,Camiseta Nike Essential Masculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5% off,4.3,NaN
1,Camiseta Nike Liverpool Club Essential Masculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5% off,5.0,NaN
2,Camiseta Nike Dri-FIT Masculina,Treino & Academia,"R$ 208,99 no Pix","R$ 329,99",37% off,NaN,NaN
3,Camiseta Nike Sportswear Tech Pack Masculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35% off,5.0,NaN
4,Camiseta Nike Dri-FIT LeBron Masculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43% off,5.0,NaN
...,...,...,...,...,...,...,...
1031,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20% off,4.1,NaN
1032,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1,NaN
1033,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12% off,4.1,NaN
1034,Jaqueta Nike Dri-FIT Corinthians Repel Academy...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48% off,4.4,NaN
1035,Camiseta Regata Nike Corinthians Masculina,Futebol,"R$ 218,49 no Pix","R$ 399,99",45% off,NaN,NaN

In [3]:
#Drop colunas sem dados
df = df.drop(columns= [" "])
df

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao
0,Camiseta Nike Essential Masculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5% off,4.3
1,Camiseta Nike Liverpool Club Essential Masculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5% off,5.0
2,Camiseta Nike Dri-FIT Masculina,Treino & Academia,"R$ 208,99 no Pix","R$ 329,99",37% off,NaN
3,Camiseta Nike Sportswear Tech Pack Masculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35% off,5.0
4,Camiseta Nike Dri-FIT LeBron Masculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43% off,5.0
...,...,...,...,...,...,...
1031,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20% off,4.1
1032,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1
1033,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12% off,4.1
1034,Jaqueta Nike Dri-FIT Corinthians Repel Academy...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48% off,4.4
1035,Camiseta Regata Nike Corinthians Masculina,Futebol,"R$ 218,49 no Pix","R$ 399,99",45% off,NaN

In [4]:
#nulos
df = df.dropna()
df

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao
0,Camiseta Nike Essential Masculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5% off,4.3
1,Camiseta Nike Liverpool Club Essential Masculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5% off,5.0
3,Camiseta Nike Sportswear Tech Pack Masculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35% off,5.0
4,Camiseta Nike Dri-FIT LeBron Masculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43% off,5.0
5,Camiseta Nike Dri-FIT ADV Masculina,Treino & Academia,"R$ 341,99 no Pix","R$ 449,99",24% off,4.3
...,...,...,...,...,...,...
1030,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1
1031,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20% off,4.1
1032,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1
1033,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12% off,4.1
1034,Jaqueta Nike Dri-FIT Corinthians Repel Academy...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48% off,4.4

In [5]:
#Drop duplicados
df = df.drop_duplicates()
df

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao
0,Camiseta Nike Essential Masculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5% off,4.3
1,Camiseta Nike Liverpool Club Essential Masculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5% off,5.0
3,Camiseta Nike Sportswear Tech Pack Masculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35% off,5.0
4,Camiseta Nike Dri-FIT LeBron Masculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43% off,5.0
5,Camiseta Nike Dri-FIT ADV Masculina,Treino & Academia,"R$ 341,99 no Pix","R$ 449,99",24% off,4.3
...,...,...,...,...,...,...
1024,Camisa Nike Dri-FIT Uniformes,Futebol,"R$ 75,99 no Pix","R$ 149,99",49% off,4.3
1028,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1
1029,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20% off,4.1
1033,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12% off,4.1
1034,Jaqueta Nike Dri-FIT Corinthians Repel Academy...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48% off,4.4

In [6]:
df['Tipo'] = df['Nome'].str.split().str[0]

/var/folders/m4/q93x5mln4l109zsf2n5yq6vr0000gn/T/ipykernel_1263/3187083619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Tipo'] = df['Nome'].str.split().str[0]

In [7]:
df

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,Camiseta Nike Essential Masculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5% off,4.3,Camiseta
1,Camiseta Nike Liverpool Club Essential Masculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5% off,5.0,Camiseta
3,Camiseta Nike Sportswear Tech Pack Masculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35% off,5.0,Camiseta
4,Camiseta Nike Dri-FIT LeBron Masculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43% off,5.0,Camiseta
5,Camiseta Nike Dri-FIT ADV Masculina,Treino & Academia,"R$ 341,99 no Pix","R$ 449,99",24% off,4.3,Camiseta
...,...,...,...,...,...,...,...
1024,Camisa Nike Dri-FIT Uniformes,Futebol,"R$ 75,99 no Pix","R$ 149,99",49% off,4.3,Camisa
1028,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42% off,4.1,Camiseta
1029,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20% off,4.1,Camiseta
1033,Camiseta Nike Dri-FIT Legend Masculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12% off,4.1,Camiseta
1034,Jaqueta Nike Dri-FIT Corinthians Repel Academy...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48% off,4.4,Jaqueta

In [8]:
#resetar o index
df2 = df.reset_index(drop=True)

In [9]:
#Unidecode
df2["Nome"] = df2["Nome"].apply(lambda x: re.sub(r'[^a-zA-Z0-9]','', unidecode (x)))
df2["Porcentagem desc"] = df2["Porcentagem desc"].apply(lambda x: re.sub(r'[^a-zA-Z0-9]','', unidecode (x)))
df2["Tipo"] = df2["Tipo"].apply(lambda x: re.sub(r'[^a-zA-Z0-9]','', unidecode (x)))
df2

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,"R$ 237,49 no Pix","R$ 249,99",5off,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,"R$ 189,99 no Pix","R$ 199,99",5off,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,"R$ 313,49 no Pix","R$ 479,99",35off,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,"R$ 142,49 no Pix","R$ 249,99",43off,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,"R$ 341,99 no Pix","R$ 449,99",24off,4.3,Camiseta
...,...,...,...,...,...,...,...
394,CamisaNikeDriFITUniformes,Futebol,"R$ 75,99 no Pix","R$ 149,99",49off,4.3,Camisa
395,CamisetaNikeDriFITLegendMasculina,Treino & Academia,"R$ 75,99 no Pix","R$ 129,99",42off,4.1,Camiseta
396,CamisetaNikeDriFITLegendMasculina,Treino & Academia,"R$ 104,49 no Pix","R$ 129,99",20off,4.1,Camiseta
397,CamisetaNikeDriFITLegendMasculina,Treino & Academia,"R$ 113,99 no Pix","R$ 129,99",12off,4.1,Camiseta
398,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,"R$ 313,49 no Pix","R$ 599,99",48off,4.4,Jaqueta

In [10]:
#Retirar strings 
df2["Valor c desc"] = df2["Valor c desc"].str.replace("R$", "").str.replace("no Pix", "").str.replace(",", "")
df2["Valor s desc"] = df2["Valor s desc"].str.replace("R$", "").str.replace(",", "")
df2["Porcentagem desc"] = df2["Porcentagem desc"].str.replace("off", "")
df2 = df2[~df2['Nome'].str.contains('Personalize', na=False)]
df2 = df2[~df2['Avaliacao'].str.contains('DisponÃ­vel em SNKRS', na=False)]
df2

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,23749,24999,5,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,18999,19999,5,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,31349,47999,35,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,14249,24999,43,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,34199,44999,24,4.3,Camiseta
...,...,...,...,...,...,...,...
394,CamisaNikeDriFITUniformes,Futebol,7599,14999,49,4.3,Camisa
395,CamisetaNikeDriFITLegendMasculina,Treino & Academia,7599,12999,42,4.1,Camiseta
396,CamisetaNikeDriFITLegendMasculina,Treino & Academia,10449,12999,20,4.1,Camiseta
397,CamisetaNikeDriFITLegendMasculina,Treino & Academia,11399,12999,12,4.1,Camiseta
398,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,31349,59999,48,4.4,Jaqueta

In [11]:
#transformar strings em valores numericos
df2 ["Porcentagem desc"] = df2 ["Porcentagem desc"].astype(float)
df2["Valor s desc"] = df2["Valor s desc"].astype(float)
df2["Valor c desc"] = df2["Valor c desc"].astype(float)
df2["Avaliacao"] = pd.to_numeric(df2["Avaliacao"])
df2

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,23749.0,24999.0,5.0,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,18999.0,19999.0,5.0,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,31349.0,47999.0,35.0,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,14249.0,24999.0,43.0,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,34199.0,44999.0,24.0,4.3,Camiseta
...,...,...,...,...,...,...,...
394,CamisaNikeDriFITUniformes,Futebol,7599.0,14999.0,49.0,4.3,Camisa
395,CamisetaNikeDriFITLegendMasculina,Treino & Academia,7599.0,12999.0,42.0,4.1,Camiseta
396,CamisetaNikeDriFITLegendMasculina,Treino & Academia,10449.0,12999.0,20.0,4.1,Camiseta
397,CamisetaNikeDriFITLegendMasculina,Treino & Academia,11399.0,12999.0,12.0,4.1,Camiseta
398,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,31349.0,59999.0,48.0,4.4,Jaqueta

In [12]:
#DivisÃ£o para os valores float nÃ£o ficarem altos demais
df2["Valor c desc"] = df2["Valor c desc"]/100
df2["Valor s desc"] = df2["Valor s desc"]/100
df2

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,237.49,249.99,5.0,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,189.99,199.99,5.0,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,313.49,479.99,35.0,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,142.49,249.99,43.0,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,341.99,449.99,24.0,4.3,Camiseta
...,...,...,...,...,...,...,...
394,CamisaNikeDriFITUniformes,Futebol,75.99,149.99,49.0,4.3,Camisa
395,CamisetaNikeDriFITLegendMasculina,Treino & Academia,75.99,129.99,42.0,4.1,Camiseta
396,CamisetaNikeDriFITLegendMasculina,Treino & Academia,104.49,129.99,20.0,4.1,Camiseta
397,CamisetaNikeDriFITLegendMasculina,Treino & Academia,113.99,129.99,12.0,4.1,Camiseta
398,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,313.49,599.99,48.0,4.4,Jaqueta

In [13]:
#Reset index de novo?
df3 = df2.reset_index(drop=True)
df3

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,237.49,249.99,5.0,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,189.99,199.99,5.0,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,313.49,479.99,35.0,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,142.49,249.99,43.0,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,341.99,449.99,24.0,4.3,Camiseta
...,...,...,...,...,...,...,...
384,CamisaNikeDriFITUniformes,Futebol,75.99,149.99,49.0,4.3,Camisa
385,CamisetaNikeDriFITLegendMasculina,Treino & Academia,75.99,129.99,42.0,4.1,Camiseta
386,CamisetaNikeDriFITLegendMasculina,Treino & Academia,104.49,129.99,20.0,4.1,Camiseta
387,CamisetaNikeDriFITLegendMasculina,Treino & Academia,113.99,129.99,12.0,4.1,Camiseta
388,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,313.49,599.99,48.0,4.4,Jaqueta

In [14]:
# Descobrir outliers
valorQ1 = df3['Valor c desc'].quantile(0.25)
valorQ3 = df3['Valor c desc'].quantile(0.75)
IQRvalor = valorQ3 - valorQ1

# Identificando os limites para os outliers
valor_minimo = valorQ1 - 1.5 * IQRvalor
valor_maximo = valorQ3 + 1.5 * IQRvalor

# Filtrando os outliers
outliers_valor = df3[(df3['Valor c desc'] < valor_minimo) | (df3['Valor c desc'] > valor_maximo)]

outliers_valor

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
17,JaquetaNikeThermaFITPufferMasculina,Casual,797.99,849.990,6.0,5.0,Jaqueta
30,JaquetaNikeParisSaintGermanMasculina,Futebol,759.99,799.990,5.0,5.0,Jaqueta
38,JaquetaNikeSportswearSherpaMasculina,Casual,854.99,899.990,5.0,3.0,Jaqueta
44,NikexMMW,Casual,1130.49,0.012,6.0,5.0,Nike
55,CamisaNikeParisSaintGermainI202324JogadorMascu...,Futebol,664.99,699.990,5.0,4.5,Camisa
58,CalcaNikeBrasilStrikeEliteMasculina,Futebol,664.99,699.990,5.0,5.0,Calca
107,JaquetaNikeTrailGoreTexInfiniumtmMasculina,Corrida,873.99,0.016,45.0,5.0,Jaqueta
162,JaquetaNikeRepelWindrunnerMasculina,Corrida,759.99,799.990,5.0,1.0,Jaqueta
287,JaquetaNikeSportswearWindrunnerMasculina,Casual,759.99,799.990,5.0,4.8,Jaqueta
312,JaquetaNikeBrasilSwooshMasculina,Futebol,683.99,799.990,15.0,4.0,Jaqueta
341,Nocta,Casual,1899.99,0.020,5.0,5.0,Nocta

In [15]:
descQ1 = df3["Porcentagem desc"].quantile(0.25)
descQ2 = df3["Porcentagem desc"].quantile(0.75)
IQRdesc = descQ2 - descQ1

desc_minimo = descQ1 - 1.5 * IQRdesc
desc_maximo = descQ2 + 1.5 * IQRdesc

outlier_desc = df3[(df3["Porcentagem desc"] < desc_minimo)|(df3["Porcentagem desc"] > desc_maximo)]

print (outlier_desc)

Empty DataFrame
Columns: [Nome, Modelo, Valor c desc, Valor s desc, Porcentagem desc, Avaliacao, Tipo]
Index: []

In [16]:
avQ1 = df3["Avaliacao"].quantile(0.25)
avQ2 = df3["Avaliacao"].quantile(0.75)
IQRav = avQ2 - avQ1

avaliacao_minimo = avQ1 - 1.5 * IQRav
avaliacao_maximo = avQ2 + 1.5 * IQRav

outliers_avaliacao = df3[(df3["Avaliacao"] < avaliacao_minimo) | (df3["Avaliacao"] > avaliacao_maximo)]
print (outliers_avaliacao)

                                                Nome             Modelo  \
7         CamisaNikeLiverpoolI202223JogadorMasculina            Futebol
11                 CamisetaNikeBrooklynNetsMasculina           Basquete
19              CamisetaNikeLiverpoolStrikeMasculina            Futebol
32   BlusaoNikeThermaFITNBALosAngelesLakersMasculino           Basquete
35                     CalcaNikeACGWolfTreeMasculina             Casual
38              JaquetaNikeSportswearSherpaMasculina             Casual
47    ShortsNikeDriFITRunDivisionChallengerMasculino            Corrida
63      CamisetaNikeParisSaintGermainStrikeMasculina            Futebol
98      CamisaNikeCoreiaII202425TorcedorProMasculina            Futebol
124                   CalcaJordanSportWovenMasculina             Casual
150             CamisetaNikeSportswearMax90Masculina             Casual
154                    ShortsNikeIconDriFITMasculino           Basquete
161              JaquetaNikeRepelWindrunnerMasculina            Corrida
162              JaquetaNikeRepelWindrunnerMasculina            Corrida
163              JaquetaNikeRepelWindrunnerMasculina            Corrida
181        CamisetaJordanMiamiHeatEssentialMasculina             Casual
183               ShortsNikeCourtDriFITSlamMasculino   Para Jogar TÃªnis
184               ShortsNikeCourtDriFITSlamMasculino   Para Jogar TÃªnis
187                      CamisetaNikeDriFITMasculina  Treino & Academia
188                      CamisetaNikeDriFITMasculina  Treino & Academia
208                   CamisetaNikeNBATeam31Masculina           Basquete
214              ShortsNikeLosAngelesLakersMasculino           Basquete
220       JaquetaNikeACGWindproofCinderConeMasculina             Casual
245         CamisetaNikeEssentialHydroguardMasculina    NataÃ§Ã£o & Praia
249                  CamisetaNikeSportswearMasculina             Casual
250                  CamisetaNikeSportswearMasculina             Casual
272            CamisetaNikeCorinthiansMax90Masculina            Futebol
273                  CalcaNikeACGCinderConeMasculina             Casual
281               CamisetaNikeDriFITUVMilerMasculina            Corrida
282               CamisetaNikeDriFITUVMilerMasculina            Corrida
283                        RegataNikeDriFITMasculina           Basquete
284                        RegataNikeDriFITMasculina           Basquete
308              CamisetaNikeBrasilJustDoItMasculina            Futebol
314             ShortsNikeStudio72UnlimitedMasculino  Treino & Academia
315             ShortsNikeStudio72UnlimitedMasculino  Treino & Academia
316                     ShortsNikeClubChinoMasculino             Casual
317                     ShortsNikeClubChinoMasculino             Casual
346        ShortsNikeCorinthiansTorcedorProMasculino            Futebol
355           CamisetaNikeDriFITUVUVHyverseMasculina  Treino & Academia

     Valor c desc  Valor s desc  Porcentagem desc  Avaliacao      Tipo
7          569.99        599.99               5.0        3.0    Camisa
11         170.99        229.99              26.0        3.0  Camiseta
19         256.49        279.99               8.0        2.0  Camiseta
32         569.99        599.99               5.0        2.0    Blusao
35         607.99        799.99              24.0        3.0     Calca
38         854.99        899.99               5.0        3.0   Jaqueta
47         208.99        299.99              30.0        1.0    Shorts
63         284.99        299.99               5.0        2.0  Camiseta
98         379.99        399.99               5.0        2.0    Camisa
124        322.99        399.99              19.0        3.0     Calca
150        151.99        229.99              34.0        2.3  Camiseta
154        123.49        229.99              46.0        2.4    Shorts
161        503.49        799.99              37.0        1.0   Jaqueta
162        759.99        799.99               5.0        1.0   Jaqueta
163        617.49        799.99              23.0        1.0   Jaqueta
181        142.49        229.99              38.0        1.0  Camiseta
183        294.49        549.99              46.0        1.0    Shorts
184        389.49        549.99              29.0        1.0    Shorts
187        170.99        249.99              32.0        3.0  Camiseta
188        180.49        249.99              28.0        3.0  Camiseta
208        265.99        279.99               5.0        1.0  Camiseta
214        199.49        299.99              34.0        2.7    Shorts
220        626.99        949.99              34.0        3.0   Jaqueta
245        151.99        159.99               5.0        3.0  Camiseta
249        199.49        229.99              13.0        1.0  Camiseta
250        189.99        229.99              17.0        1.0  Camiseta
272        161.49        299.99              46.0        3.0  Camiseta
273        303.99        599.99              49.0        3.0     Calca
281        161.49        249.99              35.0        3.0  Camiseta
282        151.99        249.99              39.0        3.0  Camiseta
283        151.99        199.99              24.0        2.7    Regata
284        123.49        199.99              38.0        2.7    Regata
308        161.49        249.99              35.0        3.0  Camiseta
314        284.99        399.99              29.0        2.0    Shorts
315        294.49        399.99              26.0        2.0    Shorts
316        379.99        399.99               5.0        2.5    Shorts
317        284.99        399.99              29.0        2.5    Shorts
346        284.99        299.99               5.0        3.0    Shorts
355        189.99        249.99              24.0        1.0  Camiseta

In [17]:

df4 = df3[(df3['Valor c desc'] >= valor_minimo) & (df3['Valor c desc'] <= valor_maximo)]
df4

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,237.49,249.99,5.0,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,189.99,199.99,5.0,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,313.49,479.99,35.0,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,142.49,249.99,43.0,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,341.99,449.99,24.0,4.3,Camiseta
...,...,...,...,...,...,...,...
384,CamisaNikeDriFITUniformes,Futebol,75.99,149.99,49.0,4.3,Camisa
385,CamisetaNikeDriFITLegendMasculina,Treino & Academia,75.99,129.99,42.0,4.1,Camiseta
386,CamisetaNikeDriFITLegendMasculina,Treino & Academia,104.49,129.99,20.0,4.1,Camiseta
387,CamisetaNikeDriFITLegendMasculina,Treino & Academia,113.99,129.99,12.0,4.1,Camiseta
388,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,313.49,599.99,48.0,4.4,Jaqueta

In [18]:
#Ultimo reset index
dffinal = df4.reset_index(drop= True)

In [19]:
dffinal.to_csv("../1_Base_tratada/nikefinal.csv", sep= ";", index=False)

In [20]:
engine = engine = create_engine('sqlite:///banconike.db', echo = True)

In [21]:
dffinal.to_sql('Dados', con  = engine, if_exists='replace', index=False)

2024-11-23 11:45:19,328 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-23 11:45:19,330 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Dados")
2024-11-23 11:45:19,331 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,332 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Dados")
2024-11-23 11:45:19,332 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,332 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite~_%' ESCAPE '~' ORDER BY name
2024-11-23 11:45:19,332 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,333 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='view' AND name NOT LIKE 'sqlite~_%' ESCAPE '~' ORDER BY name
2024-11-23 11:45:19,334 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,335 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("Dados")
2024-11-23 11:45:19,335 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,336 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type in ('table', 'view')
2024-11-23 11:45:19,336 INFO sqlalchemy.engine.Engine [raw sql] ('Dados',)
2024-11-23 11:45:19,337 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("Dados")
2024-11-23 11:45:19,337 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,337 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("Dados")
2024-11-23 11:45:19,337 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,338 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type in ('table', 'view')
2024-11-23 11:45:19,338 INFO sqlalchemy.engine.Engine [raw sql] ('Dados',)
2024-11-23 11:45:19,339 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("Dados")
2024-11-23 11:45:19,339 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,340 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("Dados")
2024-11-23 11:45:19,340 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,340 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Dados")
2024-11-23 11:45:19,340 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,341 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("Dados")
2024-11-23 11:45:19,341 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,341 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("Dados")
2024-11-23 11:45:19,342 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,342 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Dados")
2024-11-23 11:45:19,342 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,343 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type in ('table', 'view')
2024-11-23 11:45:19,343 INFO sqlalchemy.engine.Engine [raw sql] ('Dados',)
2024-11-23 11:45:19,344 INFO sqlalchemy.engine.Engine
DROP TABLE "Dados"
2024-11-23 11:45:19,344 INFO sqlalchemy.engine.Engine [no key 0.00025s] ()
2024-11-23 11:45:19,346 INFO sqlalchemy.engine.Engine
CREATE TABLE "Dados" (
	"Nome" TEXT,
	"Modelo" TEXT,
	"Valor c desc" FLOAT,
	"Valor s desc" FLOAT,
	"Porcentagem desc" FLOAT,
	"Avaliacao" FLOAT,
	"Tipo" TEXT
)


2024-11-23 11:45:19,346 INFO sqlalchemy.engine.Engine [no key 0.00019s] ()
2024-11-23 11:45:19,350 INFO sqlalchemy.engine.Engine INSERT INTO "Dados" ("Nome", "Modelo", "Valor c desc", "Valor s desc", "Porcentagem desc", "Avaliacao", "Tipo") VALUES (?, ?, ?, ?, ?, ?, ?)
2024-11-23 11:45:19,351 INFO sqlalchemy.engine.Engine [generated in 0.00232s] [('CamisetaNikeEssentialMasculina', 'Basquete', 237.49, 249.99, 5.0, 4.3, 'Camiseta'), ('CamisetaNikeLiverpoolClubEssentialMasculina', 'Futebol', 189.99, 199.99, 5.0, 5.0, 'Camiseta'), ('CamisetaNikeSportswearTechPackMasculina', 'Casual', 313.49, 479.99, 35.0, 5.0, 'Camiseta'), ('CamisetaNikeDriFITLeBronMasculina', 'Basquete', 142.49, 249.99, 43.0, 5.0, 'Camiseta'), ('CamisetaNikeDriFITADVMasculina', 'Treino & Academia', 341.99, 449.99, 24.0, 4.3, 'Camiseta'), ('CamisetaNikeClubMasculina', 'Casual', 218.49, 229.99, 5.0, 3.9, 'Camiseta'), ('CamisetaNikeMilwaukeeBucksCityEditionMasculina', 'Basquete', 189.99, 229.99, 17.0, 5.0, 'Camiseta'), ('CamisaNikeLiverpoolI202223JogadorMasculina', 'Futebol', 569.99, 599.99, 5.0, 3.0, 'Camisa')  ... displaying 10 of 378 total bound parameter sets ...  ('CamisetaNikeDriFITLegendMasculina', 'Treino & Academia', 113.99, 129.99, 12.0, 4.1, 'Camiseta'), ('JaquetaNikeDriFITCorinthiansRepelAcademyIIIMasculina', 'Futebol', 313.49, 599.99, 48.0, 4.4, 'Jaqueta')]
2024-11-23 11:45:19,353 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite~_%' ESCAPE '~' ORDER BY name
2024-11-23 11:45:19,354 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,354 INFO sqlalchemy.engine.Engine COMMIT

378

In [22]:
dflido = pd.read_sql('SELECT * FROM Dados', con = engine)
dflido

2024-11-23 11:45:19,360 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-11-23 11:45:19,362 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("SELECT * FROM Dados")
2024-11-23 11:45:19,362 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,363 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("SELECT * FROM Dados")
2024-11-23 11:45:19,364 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,365 INFO sqlalchemy.engine.Engine SELECT * FROM Dados
2024-11-23 11:45:19,365 INFO sqlalchemy.engine.Engine [raw sql] ()
2024-11-23 11:45:19,368 INFO sqlalchemy.engine.Engine ROLLBACK

,Nome,Modelo,Valor c desc,Valor s desc,Porcentagem desc,Avaliacao,Tipo
0,CamisetaNikeEssentialMasculina,Basquete,237.49,249.99,5.0,4.3,Camiseta
1,CamisetaNikeLiverpoolClubEssentialMasculina,Futebol,189.99,199.99,5.0,5.0,Camiseta
2,CamisetaNikeSportswearTechPackMasculina,Casual,313.49,479.99,35.0,5.0,Camiseta
3,CamisetaNikeDriFITLeBronMasculina,Basquete,142.49,249.99,43.0,5.0,Camiseta
4,CamisetaNikeDriFITADVMasculina,Treino & Academia,341.99,449.99,24.0,4.3,Camiseta
...,...,...,...,...,...,...,...
373,CamisaNikeDriFITUniformes,Futebol,75.99,149.99,49.0,4.3,Camisa
374,CamisetaNikeDriFITLegendMasculina,Treino & Academia,75.99,129.99,42.0,4.1,Camiseta
375,CamisetaNikeDriFITLegendMasculina,Treino & Academia,104.49,129.99,20.0,4.1,Camiseta
376,CamisetaNikeDriFITLegendMasculina,Treino & Academia,113.99,129.99,12.0,4.1,Camiseta
377,JaquetaNikeDriFITCorinthiansRepelAcademyIIIMas...,Futebol,313.49,599.99,48.0,4.4,Jaqueta